language: node_js
before_script:
  - npm install -g gulp
node_js:
  - "stable"
script:
  - gulp build
addons:
  apt:
    packages:
    - wine
before_deploy:
  - gem install mime-types -v 2.6.2
  - gulp package-win32
deploy:
  provider: releases
  api_key: '$GH_KEY'
  file: ./installer/fb-messenger-setup.exe
  skip_cleanup: true
  on:
    tags: true