language: node_js
cache:
  directories:
  - electron/cache/v0.35.0
  - node_modules/electron-prebuilt
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install
before_script:
  - npm install -g gulp
node_js:
  - "stable"
script:
  - if [ "$TRAVIS_TAG" = "" ]; then gulp build; else gulp package-win32; fi
addons:
  apt:
    packages:
    - wine
    - xvfb
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key: '$GH_KEY'
  file: ./installer/fb-messenger-setup.exe
  skip_cleanup: true
  on:
    tags: true